/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as InsuranceIndexRouteImport } from './routes/insurance.index'
import { Route as InsuranceSlugRouteImport } from './routes/insurance.$slug'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as LoansSlugRouteImport } from './routes/loans.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceIndexRoute = InsuranceIndexRouteImport.update({
  id: '/insurance/',
  path: '/insurance/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceSlugRoute = InsuranceSlugRouteImport.update({
  id: '/insurance/$slug',
  path: '/insurance/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansSlugRoute = LoansSlugRouteImport.update({
  id: '/loans/$slug',
  path: '/loans/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/investments': typeof InvestmentsRoute
  '/partner': typeof PartnerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/insurance/$slug': typeof InsuranceSlugRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/investments': typeof InvestmentsRoute
  '/partner': typeof PartnerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/insurance/$slug': typeof InsuranceSlugRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/insurance': typeof InsuranceIndexRoute
  '/loans': typeof LoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/investments': typeof InvestmentsRoute
  '/partner': typeof PartnerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/insurance/$slug': typeof InsuranceSlugRoute
  '/loans/$slug': typeof LoansSlugRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/how-it-works'
    | '/investments'
    | '/partner'
    | '/privacy-policy'
    | '/terms'
    | '/insurance/$slug'
    | '/loans/$slug'
    | '/insurance/'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/how-it-works'
    | '/investments'
    | '/partner'
    | '/privacy-policy'
    | '/terms'
    | '/insurance/$slug'
    | '/loans/$slug'
    | '/insurance'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/how-it-works'
    | '/investments'
    | '/partner'
    | '/privacy-policy'
    | '/terms'
    | '/insurance/$slug'
    | '/loans/$slug'
    | '/insurance/'
    | '/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InvestmentsRoute: typeof InvestmentsRoute
  PartnerRoute: typeof PartnerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  InsuranceSlugRoute: typeof InsuranceSlugRoute
  LoansSlugRoute: typeof LoansSlugRoute
  InsuranceIndexRoute: typeof InsuranceIndexRoute
  LoansIndexRoute: typeof LoansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/': {
      id: '/insurance/'
      path: '/insurance'
      fullPath: '/insurance/'
      preLoaderRoute: typeof InsuranceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/$slug': {
      id: '/insurance/$slug'
      path: '/insurance/$slug'
      fullPath: '/insurance/$slug'
      preLoaderRoute: typeof InsuranceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$slug': {
      id: '/loans/$slug'
      path: '/loans/$slug'
      fullPath: '/loans/$slug'
      preLoaderRoute: typeof LoansSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  HowItWorksRoute: HowItWorksRoute,
  InvestmentsRoute: InvestmentsRoute,
  PartnerRoute: PartnerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  InsuranceSlugRoute: InsuranceSlugRoute,
  LoansSlugRoute: LoansSlugRoute,
  InsuranceIndexRoute: InsuranceIndexRoute,
  LoansIndexRoute: LoansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
